changelog:
  categories:
    - title: Features
      labels:
        - "*"
    - title: Bug fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependency
    - title: Internal changes
      labels:
        - internal
