changelog:
  categories:
    - title: Features
      labels:
        - "*"
      exclude:
        labels:
          - bug
          - dependency
          - internal
    - title: Bug fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependency
    - title: Internal changes
      labels:
        - internal
