name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Build
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build
