name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Build
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Run build
        run: pnpm run build
