name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build
