name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Install TypeScript ${{ matrix.ts-version }}
        run: pnpm add typescript@${{ matrix.ts-version }}

      - name: Run tests
        run: pnpm run test
