name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test with TypeScript ${{ matrix.ts-version }}
    strategy:
      matrix:
        ts-version:
          - "4.8"
          - "4.7"
          - "4.6"
          - "4.5"
          - "4.4"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Install TypeScript ${{ matrix.ts-version }}
        run: pnpm add typescript@${{ matrix.ts-version }}

      - name: Run tests
        run: pnpm run test
