name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        ts-version:
          - "4.4.x"
          - "4.5.x"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Install TypeScript ${{ matrix.ts-version }}
        run: npm install typescript@${{ matrix.ts-version }}

      - name: Run tests
        run: npm run test
